# Generated by Django 4.0.3 on 2022-03-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogDevBranchAPP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormalArticleTopic',
        ),
    ]
