# Generated by Django 4.0.3 on 2022-03-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogDevBranchAPP', '0002_delete_normalarticletopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalArticleTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('date_var', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
