# Generated by Django 4.0.3 on 2022-03-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogDevBranchAPP', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalArticleTopicEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_var', models.DateField(auto_now_add=True)),
                ('topics', models.ForeignKey(on_delete=models.SET('DELETED'), to='blogDevBranchAPP.normalarticletopic')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
